name: whitesupermarketapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+17

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  intl: ^0.19.0
  flutter_image_slider: ^0.0.2
  share_plus: ^10.0.2
  url_launcher: ^6.2.5
  auto_animated: ^3.1.0
  draggable_fab: ^0.1.4
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.1.2
  mongo_dart: ^0.10.1
  carousel_slider: ^5.0.0
  twilio_flutter: ^0.9.0
  http: ^1.2.0
  mailer: ^6.1.0
  pdf: ^3.10.8
  printing: ^5.12.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  flutter_native_splash: ^2.4.3
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  cloudinary: ^1.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_launcher_icons: "^0.13.1"
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# flutter_native_splash:
#   color: "#302F7F" # Background color
#   image: assets/logo/nativelogo.png # Path to your splash logo

#   android_12:
#     image: assets/logo/nativelogo.png
#     color: "#302F7F"
    

#     # color_android: "#302F7F"
#     android_gravity: center

#   web: true


#   fullscreen: true # Optional, makes it fullscreen


#flutter_launcher_icons:
#  android: "launcher_icon"
#  ios: true
#  image_path: "assets/logo/logo1.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/logo/
    - assets/images/
    - assets/category_images/
    - assets/gif/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  


